### ISSUE TITLE
Add more automated checks to import process

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#1045]
A lot of the overhead of this project near to elections is around basic consistency checks on the data. We should automate as many of these as possible. We should throw some kind of error or warning when:

- [x] ~A station point is outside target local auth~ (done in PR #1034 )
- [x] A polling district wholly or mostly falls outside the target local auth boundary (refs #666, #667) (PR #1203 )
- [x] A `ResidentialAddress` falls outside the target local auth boundary (how do we do this quickly? Checking every address one-by-one is going to be really slow)
- [ ] The data we've imported only covers part of the local authority (need a proxy for this e.g: wards with 0 addresses in them)
- [x] ~Number of records 'looks right' based on total number of addresses in local auth (bit 'finger in the air' but should be able to work out a plausible-ish percentage and warn if below)~ #1122

..anything else?

**Comment by symroe** [comment]
> A ResidentialAddress falls outside the target local auth boundary 

Maybe with http://postgis.net/docs/ST_Disjoint.html?

**Comment by chris48s** [comment]
It would also be useful to be able to detect/fix polling distirct boundaries which don't clip precisely to local auth boundaries, but this is a soft error - sometimes it matters more than others.
e.g: if a boundary in a coastal local auth clips to the coastline but we've got a full extent boundary then that is a different class of error than a polling district for a London borough grabbing a couple of streets from its' neighbouring local auth.

**Comment by chris48s** [comment]
* `ResidentialAddress` record has incorrect postcode attached (can we check input postcodes against AddressBase where input record has UPRN?) This will at least help to catch some cases.

**Comment by chris48s** [comment]
> A polling district wholly or mostly falls outside the target local auth boundary

Use https://postgis.net/docs/ST_PointOnSurface.html + check if point is inside or outside (centroid is not a good plan because C-shaped or U-shaped polygons may have a centroid outside the polygon).

**Comment by chris48s** [comment]
> A polling district wholly or mostly falls outside the target local auth boundary

given 2 geometries `pollingdistrict`, `localauth`: if `localauth` doesn't contain or intersect, `pollingdistrict` its wholly outside. If it contains its wholly inside. If it intersects, `intersection = pollingdistrict.intersection(localauth)` gives you the bit of `pollingdistrict` inside `localauth` and you can compare `pollingdistrict.area` to `intersection.area` to work out the size of the overlap and report it.

**Comment by chris48s** [comment]
> A `ResidentialAddress` falls outside the target local auth boundary (how do we do this quickly? Checking every address one-by-one is going to be really slow)

Now that we've got the UPRNS in, we can narrow the search space. In this code block:

https://github.com/DemocracyClub/UK-Polling-Stations/blob/56bea09b15df70f761b6dd9aceea22c178ed59a2/polling_stations/apps/data_collection/data_types.py#L219-L242

If a record is in `addressbase_data` and the postcodes match, we know that the `ResidentialAddress` is inside the target auth. We only need to check the subset that either aren't in `addressbase_data` or where the postcodes don't match.

**Comment by chris48s** [comment]
Going to close this one off as the check for "Number of records 'looks right'" also helps with identifying partial data. I think all the major points here are now addressed.
