### ISSUE TITLE
Feature: Support "Advance Voting"

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#4181]
# Background
 
The Welsh Government are piloting "Advance Voting": voting in advance of polling day at defined locations.

[Welsh government statement and update on Flexible Voting Pilots](https://gov.wales/written-statement-update-flexible-voting-pilots)

The areas are:

> **Blaenau Gwent** – the centrally-located Ebbw Vale Learning Zone will be used as an advanced polling station for all residents of the county, including students of the college. Advance voting will be available during the week leading to Election Day.
> 
> **Bridgend** - polling stations in certain low turnout wards will be open for advanced voting during the week leading up to Election Day   A new polling station will also be created in a school for registered students at that school only.
> 
> **Caerphilly** – the council offices at Ystrad Mynach will be used as an advanced polling station for all residents of the county on the weekend before Election Day.
> 
> **Torfaen** –the council offices at Pontypool will be used as an advanced polling station for all residents of the county on the weekend before Election Day.

# Tasks

## Storing the data
It's likely that this pilot is continued in future years, and maybe applied to the whole of Wales. Because of this, it makes sense to find a good way of storing and managing the data.

My suggestion is that we manage this through the import scripts, and we attach the advance voting stations via an FK to the _polling station_ model. We should talk more about this, but the idea is that we are likely to want fine grained control of this in future. Some councils will have a single place for everyone, others might have different places depending on the polling station.

I think we need a new model that we can use to store some basic information like point location, address, maybe other details like opening times, directions or accessibility text. TDB depending on some research.

## Presenting the data

We need to present this data directly on the results page, next to the "normal" polling station info. It should be clear that the address is in a pilot area.

We also need to present this in the API and Widget.

- [x] Add model to store Advance Voting venues
- [x] Decide how to manage the data (via existing import scripts?)
- [x] Update front end to show Advance Voting venues on polling station results pages
- [ ] Update translations to support Advance Voting
- [x] Add to WDIV API — decide generic implementation or specific?
- [ ] Update WDIV API Docs
- [x] #4436
- [ ] https://github.com/DemocracyClub/aggregator-api/pull/296
- [ ] [WCIVF]: Update polling station card to show Advance Voting
- [ ] [Widget]: Update Widget

**Comment by symroe** [comment]
> Decide how to manage the data (via existing import scripts?)

We decided to add the data via the import scripts, in a new method. Data comes from an object in the import script

**Comment by symroe** [comment]
> Add to WDIV API — decide generic implementation or specific?

This data isn't a property of a polling station, it's a property of a postcode / address. This means we will add it as a dedicated, null-able, key at the same level as the polling station object.
